# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# we explicitly define different continuous integration stages that will run
stages:
  - build
  - test
  - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

install_dependencies:
  stage: build
  only:
    - master
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

pages:
  stage: deploy
  only:
    - master
  script:
    - echo 'Build start...'
    - npm run build
    - echo 'Build end'
  artifacts:
    paths:
      - public
      - dist
