# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10

# we explicitly define different continuous integration stages that will run
stages:
  - build
  - test
  - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

install:
  stage: build
  only:
    - master
  script:
    - npm install --dev
  artifacts:
    paths:
      - node_modules

test:
  stage: test
  only:
    - master
  script:
    # Currently there's even no 'npm test' script, so this step could be skipped
    # but let it be here for reference
    - npm test

# 'pages' is a special job that is used to upload static content to GitLab
# that can be used to serve your website. It has a special syntax,
# so the two requirements below must be met:
#   1. Any static content must be placed under a public/ directory
#   2. artifacts with a path to the public/ directory must be defined
pages:
  stage: deploy
  only:
    - master
  script:
    - npm run build
    - mv dist public
    # - cp -r dist/* public
  artifacts:
    paths:
      - public
